services:
  postgres:
    image: postgres:15-alpine
    container_name: reading_db
    environment:
      POSTGRES_USER: reading_admin
      POSTGRES_PASSWORD: securepass123
      POSTGRES_DB: reading_analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reading_admin -d reading_analytics"]
      interval: 5s
      timeout: 5s
      retries: 5

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reading_django
    command: >
      sh -c "python wait_for_db.py &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DEBUG: '1'
      SECRET_KEY: supersecretkey
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1
      POSTGRES_DB: reading_analytics
      POSTGRES_USER: reading_admin
      POSTGRES_PASSWORD: securepass123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

volumes:
  postgres_data:

networks:
  default:
    name: reading_network
