# Generated by Django 5.2.1 on 2025-05-15 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('complexity_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=50)),
                ('theme', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('program', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('pro', 'Pro')], max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateTimeField(auto_now_add=True)),
                ('reading_speed', models.PositiveIntegerField()),
                ('comprehension', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('session_data', models.JSONField()),
                ('fragment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.fragment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.user')),
            ],
        ),
    ]
